version: "3.8"
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/0976983674Tt@
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/conf:/conf
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins

  mysql:
    image: mysql:5.7.44
    container_name: mysql
    command: --max_allowed_packet=32505856
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 0976983674Tt@
      MYSQL_USER: root
      MYSQL_PASSWORD: 0976983674Tt@
      MYSQL_DATABASE: medicine
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p0976983674"]
      interval: 5s
      retries: 10
      start_period: 10s

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
